
import java.awt.event.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * ------COMENTARIOS------ Detalles de cosas que se me pueden olvidar
 *
 * RellenarLayeredPane() -para poder manejar todo en base al ArrayList botones.
 * asi
 *
 * TODO LOS CONTENEDORES DEBEN TRABAJA EN BASE A LOS ARRAYLIST - para poder
 * guardar un solo arreglo de arraylist y cargar todo
 *
 *
 * forma de poner texto multilinea en botones es con html
 * "<html>linea1<br>linea2</html>"
 *
 * @author joser
 */
public class jFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFPrincipal
     */
    public jFPrincipal() {
        initComponents();

        //formate inicial de jb_colorFuente
//        JLabel label1 = createDraggableLabel("label", 100, 100);
//        jLayeredPane1.add(label1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpum_elemDiagramaFlujo = new javax.swing.JPopupMenu();
        jmi_elemDiagFljCambiarColor = new javax.swing.JMenuItem();
        jmi_elemDiagFljCambiarTexto = new javax.swing.JMenuItem();
        jmi_elemDiagFlCopiar = new javax.swing.JMenuItem();
        jmi_elemDiagFlAgregarPropiedad = new javax.swing.JMenuItem();
        jmi_elemDiagFljEliminar = new javax.swing.JMenuItem();
        jmi_elemDiagFlPropiedades = new javax.swing.JMenuItem();
        jf_ventanaCodigo = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta_codigoGenerado = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jd_crearVariable = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_nombreNuevaVariable = new javax.swing.JTextField();
        jcb_tipoNuevaVariable = new javax.swing.JComboBox<>();
        jb_agregarVariable = new javax.swing.JButton();
        jd_crearOperacion = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcb_crearOperacionVar1 = new javax.swing.JComboBox<>();
        jcb_crearOperacionOperador = new javax.swing.JComboBox<>();
        jcb_crearOperacionVar2 = new javax.swing.JComboBox<>();
        jcb_crearOperacionResultado = new javax.swing.JComboBox<>();
        jb_dialogCrearOperacion = new javax.swing.JButton();
        jp_opcionesFuente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcb_fuenteFuente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jb_fuenteColor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        js_fuenteTamaño = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jcb_fuenteEstilo = new javax.swing.JComboBox<>();
        jtp_diagramaCodigo = new javax.swing.JTabbedPane();
        jp_Diagrama = new javax.swing.JPanel();
        jp_variables = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_variables = new javax.swing.JList<>();
        jb_mostrarDialogAgregarVariable = new javax.swing.JButton();
        jp_diagramaOpciones = new javax.swing.JPanel();
        jb_opcionesInicio = new javax.swing.JButton();
        jb_opcionesDeclarar = new javax.swing.JButton();
        jb_opcionesIf = new javax.swing.JButton();
        jb_opcionesFor = new javax.swing.JButton();
        jb_opcionesWhile = new javax.swing.JButton();
        jb_opcionesSout = new javax.swing.JButton();
        jb_opcionesFin = new javax.swing.JButton();
        jb_opcionesConectorX = new javax.swing.JButton();
        jb_opcionesConectorY = new javax.swing.JButton();
        jb_generarCodigoFlujo = new javax.swing.JButton();
        jb_pegarElementoDiagramaFlujo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlp_diagramaFlujo = new javax.swing.JLayeredPane();
        jp_clases = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_clases = new javax.swing.JTree();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlp_diagramaClases = new javax.swing.JLayeredPane();
        jp_codigo = new javax.swing.JPanel();
        jmb_principal = new javax.swing.JMenuBar();
        jm_principalArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmi_archivoNuevo = new javax.swing.JMenuItem();
        jm_principalExportar = new javax.swing.JMenu();
        jmi_exportarPDF = new javax.swing.JMenuItem();

        jmi_elemDiagFljCambiarColor.setText("Cambiar Color");
        jpum_elemDiagramaFlujo.add(jmi_elemDiagFljCambiarColor);

        jmi_elemDiagFljCambiarTexto.setText("Cambiar Texto");
        jpum_elemDiagramaFlujo.add(jmi_elemDiagFljCambiarTexto);

        jmi_elemDiagFlCopiar.setText("jMenuItem6");
        jpum_elemDiagramaFlujo.add(jmi_elemDiagFlCopiar);

        jmi_elemDiagFlAgregarPropiedad.setText("jMenuItem3");
        jpum_elemDiagramaFlujo.add(jmi_elemDiagFlAgregarPropiedad);

        jmi_elemDiagFljEliminar.setText("jMenuItem3");
        jpum_elemDiagramaFlujo.add(jmi_elemDiagFljEliminar);

        jmi_elemDiagFlPropiedades.setText("xasdf");
        jpum_elemDiagramaFlujo.add(jmi_elemDiagFlPropiedades);

        jf_ventanaCodigo.setTitle("Codigo Generado");
        jf_ventanaCodigo.setMinimumSize(new java.awt.Dimension(800, 800));
        jf_ventanaCodigo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jf_ventanaCodigo.setPreferredSize(new java.awt.Dimension(800, 900));
        jf_ventanaCodigo.setSize(new java.awt.Dimension(800, 800));

        jta_codigoGenerado.setEditable(false);
        jta_codigoGenerado.setColumns(20);
        jta_codigoGenerado.setRows(5);
        jScrollPane5.setViewportView(jta_codigoGenerado);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CODIGO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel7)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jf_ventanaCodigoLayout = new javax.swing.GroupLayout(jf_ventanaCodigo.getContentPane());
        jf_ventanaCodigo.getContentPane().setLayout(jf_ventanaCodigoLayout);
        jf_ventanaCodigoLayout.setHorizontalGroup(
            jf_ventanaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jf_ventanaCodigoLayout.setVerticalGroup(
            jf_ventanaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_crearVariable.setTitle("Agregar Variable");
        jd_crearVariable.setMinimumSize(new java.awt.Dimension(350, 300));
        jd_crearVariable.setModal(true);
        jd_crearVariable.setResizable(false);

        jPanel3.setMinimumSize(new java.awt.Dimension(350, 300));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Tipo:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Nombre:");

        jcb_tipoNuevaVariable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "char", "string", "short", "double", "boolean" }));

        jb_agregarVariable.setText("Agregar");
        jb_agregarVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_nombreNuevaVariable)
                            .addComponent(jcb_tipoNuevaVariable, 0, 175, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jb_agregarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_nombreNuevaVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcb_tipoNuevaVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jb_agregarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jd_crearVariableLayout = new javax.swing.GroupLayout(jd_crearVariable.getContentPane());
        jd_crearVariable.getContentPane().setLayout(jd_crearVariableLayout);
        jd_crearVariableLayout.setHorizontalGroup(
            jd_crearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearVariableLayout.setVerticalGroup(
            jd_crearVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_crearVariable.getAccessibleContext().setAccessibleDescription("");
        jd_crearVariable.getAccessibleContext().setAccessibleParent(this);

        jd_crearOperacion.setTitle("Operacion");
        jd_crearOperacion.setMinimumSize(new java.awt.Dimension(530, 160));
        jd_crearOperacion.setModal(true);
        jd_crearOperacion.setPreferredSize(new java.awt.Dimension(530, 160));

        jPanel4.setMinimumSize(new java.awt.Dimension(530, 150));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(530, 150));

        jLabel10.setText("Variable 1");

        jLabel11.setText("Operacion");

        jLabel12.setText("Variable 2");

        jLabel13.setText("Resultado");

        jcb_crearOperacionVar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_crearOperacionVar1ActionPerformed(evt);
            }
        });

        jcb_crearOperacionOperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "/", "*" }));

        jb_dialogCrearOperacion.setText("Crear Operacion");
        jb_dialogCrearOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_dialogCrearOperacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jcb_crearOperacionVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jcb_crearOperacionOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_crearOperacionVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_crearOperacionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel12)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jb_dialogCrearOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_crearOperacionVar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_crearOperacionOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_crearOperacionVar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_crearOperacionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_dialogCrearOperacion)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearOperacionLayout = new javax.swing.GroupLayout(jd_crearOperacion.getContentPane());
        jd_crearOperacion.getContentPane().setLayout(jd_crearOperacionLayout);
        jd_crearOperacionLayout.setHorizontalGroup(
            jd_crearOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearOperacionLayout.setVerticalGroup(
            jd_crearOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jd_crearOperacion.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jp_opcionesFuente.setBackground(new java.awt.Color(204, 255, 255));
        jp_opcionesFuente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Fuente");
        jp_opcionesFuente.add(jLabel1);

        jcb_fuenteFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segoe", "Times New Roman", "Arial", "Comic Sans" }));
        jcb_fuenteFuente.setPreferredSize(new java.awt.Dimension(150, 22));
        jp_opcionesFuente.add(jcb_fuenteFuente);

        jLabel2.setText("     Color");
        jp_opcionesFuente.add(jLabel2);

        jb_fuenteColor.setText("(click)");
        jp_opcionesFuente.add(jb_fuenteColor);

        jLabel3.setText("     Tamaño");
        jp_opcionesFuente.add(jLabel3);

        js_fuenteTamaño.setPreferredSize(new java.awt.Dimension(70, 22));
        jp_opcionesFuente.add(js_fuenteTamaño);

        jLabel4.setText("     Estilo");
        jp_opcionesFuente.add(jLabel4);

        jcb_fuenteEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Negrita", "Italica" }));
        jcb_fuenteEstilo.setPreferredSize(new java.awt.Dimension(150, 22));
        jp_opcionesFuente.add(jcb_fuenteEstilo);

        jp_variables.setBackground(new java.awt.Color(204, 204, 255));
        jp_variables.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VARIABLES");

        jScrollPane1.setViewportView(jl_variables);

        jb_mostrarDialogAgregarVariable.setText("Agregar Variable");
        jb_mostrarDialogAgregarVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_mostrarDialogAgregarVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_variablesLayout = new javax.swing.GroupLayout(jp_variables);
        jp_variables.setLayout(jp_variablesLayout);
        jp_variablesLayout.setHorizontalGroup(
            jp_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_variablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jp_variablesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jp_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_mostrarDialogAgregarVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_variablesLayout.setVerticalGroup(
            jp_variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_variablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_mostrarDialogAgregarVariable)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jp_diagramaOpciones.setBackground(new java.awt.Color(255, 204, 255));
        jp_diagramaOpciones.setMinimumSize(new java.awt.Dimension(1112, 137));

        jb_opcionesInicio.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inicio.png"))); // NOI18N
        jb_opcionesInicio.setText("INICIO");
        jb_opcionesInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesInicio.setPreferredSize(new java.awt.Dimension(118, 118));
        jb_opcionesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_opcionesInicioActionPerformed(evt);
            }
        });
        jp_diagramaOpciones.add(jb_opcionesInicio);

        jb_opcionesDeclarar.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesDeclarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/declarar.png"))); // NOI18N
        jb_opcionesDeclarar.setText("DECLARAR OP.");
        jb_opcionesDeclarar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesDeclarar.setPreferredSize(new java.awt.Dimension(118, 118));
        jb_opcionesDeclarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_opcionesDeclararActionPerformed(evt);
            }
        });
        jp_diagramaOpciones.add(jb_opcionesDeclarar);

        jb_opcionesIf.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesIf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/if.png"))); // NOI18N
        jb_opcionesIf.setText("IF");
        jb_opcionesIf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesIf.setPreferredSize(new java.awt.Dimension(118, 118));
        jp_diagramaOpciones.add(jb_opcionesIf);

        jb_opcionesFor.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/for.png"))); // NOI18N
        jb_opcionesFor.setText("FOR");
        jb_opcionesFor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesFor.setPreferredSize(new java.awt.Dimension(118, 118));
        jp_diagramaOpciones.add(jb_opcionesFor);

        jb_opcionesWhile.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesWhile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/while.png"))); // NOI18N
        jb_opcionesWhile.setText("WHILE");
        jb_opcionesWhile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesWhile.setPreferredSize(new java.awt.Dimension(118, 118));
        jp_diagramaOpciones.add(jb_opcionesWhile);

        jb_opcionesSout.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesSout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sout.png"))); // NOI18N
        jb_opcionesSout.setText("S.O.U.T");
        jb_opcionesSout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesSout.setPreferredSize(new java.awt.Dimension(118, 118));
        jp_diagramaOpciones.add(jb_opcionesSout);

        jb_opcionesFin.setForeground(new java.awt.Color(0, 0, 0));
        jb_opcionesFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fin.png"))); // NOI18N
        jb_opcionesFin.setText("FIN");
        jb_opcionesFin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesFin.setPreferredSize(new java.awt.Dimension(118, 118));
        jb_opcionesFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_opcionesFinActionPerformed(evt);
            }
        });
        jp_diagramaOpciones.add(jb_opcionesFin);

        jb_opcionesConectorX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/x.png"))); // NOI18N
        jb_opcionesConectorX.setText("CONECTOR X");
        jb_opcionesConectorX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesConectorX.setPreferredSize(new java.awt.Dimension(118, 118));
        jb_opcionesConectorX.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jp_diagramaOpciones.add(jb_opcionesConectorX);

        jb_opcionesConectorY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/y.png"))); // NOI18N
        jb_opcionesConectorY.setText("CONECTOR Y");
        jb_opcionesConectorY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_opcionesConectorY.setPreferredSize(new java.awt.Dimension(118, 118));
        jp_diagramaOpciones.add(jb_opcionesConectorY);

        jb_generarCodigoFlujo.setText("Generar Codigo");
        jb_generarCodigoFlujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_generarCodigoFlujoActionPerformed(evt);
            }
        });

        jb_pegarElementoDiagramaFlujo.setText("Pegar");

        jlp_diagramaFlujo.setBackground(new java.awt.Color(204, 255, 204));
        jlp_diagramaFlujo.setForeground(new java.awt.Color(255, 255, 255));
        jlp_diagramaFlujo.setOpaque(true);
        jScrollPane4.setViewportView(jlp_diagramaFlujo);
        jlp_diagramaFlujo.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout jp_DiagramaLayout = new javax.swing.GroupLayout(jp_Diagrama);
        jp_Diagrama.setLayout(jp_DiagramaLayout);
        jp_DiagramaLayout.setHorizontalGroup(
            jp_DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DiagramaLayout.createSequentialGroup()
                .addGroup(jp_DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_diagramaOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_generarCodigoFlujo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jp_variables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_pegarElementoDiagramaFlujo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jp_DiagramaLayout.setVerticalGroup(
            jp_DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DiagramaLayout.createSequentialGroup()
                .addGroup(jp_DiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_DiagramaLayout.createSequentialGroup()
                        .addComponent(jp_diagramaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jp_DiagramaLayout.createSequentialGroup()
                        .addComponent(jp_variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jb_pegarElementoDiagramaFlujo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_generarCodigoFlujo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );

        jtp_diagramaCodigo.addTab("Diagrama de Flujo", jp_Diagrama);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jScrollPane2.setViewportView(jt_clases);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CLASES");

        jButton3.setText("Generar Codigo");

        jButton4.setText("Crear Clase");

        jButton5.setText("Definir Herencia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jlp_diagramaClases.setBackground(new java.awt.Color(204, 255, 204));
        jlp_diagramaClases.setForeground(new java.awt.Color(255, 255, 255));
        jlp_diagramaClases.setOpaque(true);
        jScrollPane3.setViewportView(jlp_diagramaClases);

        javax.swing.GroupLayout jp_clasesLayout = new javax.swing.GroupLayout(jp_clases);
        jp_clases.setLayout(jp_clasesLayout);
        jp_clasesLayout.setHorizontalGroup(
            jp_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_clasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jp_clasesLayout.setVerticalGroup(
            jp_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtp_diagramaCodigo.addTab("Diagrama de Clases", jp_clases);

        javax.swing.GroupLayout jp_codigoLayout = new javax.swing.GroupLayout(jp_codigo);
        jp_codigo.setLayout(jp_codigoLayout);
        jp_codigoLayout.setHorizontalGroup(
            jp_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1343, Short.MAX_VALUE)
        );
        jp_codigoLayout.setVerticalGroup(
            jp_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        jtp_diagramaCodigo.addTab("Código", jp_codigo);

        jm_principalArchivo.setText("Archivo");

        jMenuItem1.setText("Guardar");
        jm_principalArchivo.add(jMenuItem1);

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jm_principalArchivo.add(jMenuItem2);

        jmi_archivoNuevo.setText("Nuevo");
        jm_principalArchivo.add(jmi_archivoNuevo);

        jmb_principal.add(jm_principalArchivo);

        jm_principalExportar.setText("Exportar");

        jmi_exportarPDF.setText("Exportar PDF");
        jm_principalExportar.add(jmi_exportarPDF);

        jmb_principal.add(jm_principalExportar);

        setJMenuBar(jmb_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_opcionesFuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtp_diagramaCodigo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_opcionesFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtp_diagramaCodigo)
                .addContainerGap())
        );

        jtp_diagramaCodigo.getAccessibleContext().setAccessibleName("Diagrama");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jb_opcionesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_opcionesInicioActionPerformed
        // BOTON INICIO

        if (contBotonesInicio > 0) {
            JOptionPane.showMessageDialog(jlp_diagramaFlujo, "Solo puede existir 1\n"
                    + "inicio por programa");

        } else {
            BotonInicio nuevoInicio = (BotonInicio) convertirABotonArrastrable(new BotonInicio());
            botonesDiagramaFlujo.add(nuevoInicio);
            llenarJLayeredPane(jlp_diagramaFlujo);
            contBotonesInicio++;
            jlp_diagramaFlujo.repaint();
        }


    }//GEN-LAST:event_jb_opcionesInicioActionPerformed

    private void jb_generarCodigoFlujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_generarCodigoFlujoActionPerformed

        //1. Añadir todas las lineas de codigo al jta basandose en el arraylist
        //2. mostrar la ventana con el texto lleno
        jf_ventanaCodigo.setLocationRelativeTo(jp_Diagrama);
        jf_ventanaCodigo.setVisible(true);
        jta_codigoGenerado.setText("");

        jta_codigoGenerado.append("//Declaracion Variables\n");
        for (String variable : listaVariables) {
            String tipo = variable.split("\\)")[0].substring(1);
            String nombre = variable.split("\\)")[1];
            jta_codigoGenerado.append(tipo + " ");
            jta_codigoGenerado.append(nombre + " ;\n");
        }
        jta_codigoGenerado.append("\n\n");
        for (JButton boton : botonesDiagramaFlujo) {
            jta_codigoGenerado.append(boton.toString());
        }
    }//GEN-LAST:event_jb_generarCodigoFlujoActionPerformed

    private void jb_opcionesDeclararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_opcionesDeclararActionPerformed

        if (listaVariables.size() <= 0) {
            JOptionPane.showMessageDialog(this, "No hay variables");
        } else {
            // mostrar dialog de crear operacion
            jd_crearOperacion.setLocationRelativeTo(this);

            jcb_crearOperacionResultado.removeAllItems();
            jcb_crearOperacionVar1.removeAllItems();
            jcb_crearOperacionVar2.removeAllItems();

            //llenar cb
            for (String variable : listaVariables) {
                jcb_crearOperacionVar1.addItem(variable);
                jcb_crearOperacionVar2.addItem(variable);
                jcb_crearOperacionResultado.addItem(variable);
            }
            jcb_crearOperacionVar1.repaint();
            jcb_crearOperacionVar2.repaint();
            jcb_crearOperacionResultado.repaint();

            jd_crearOperacion.setVisible(true);
        }


    }//GEN-LAST:event_jb_opcionesDeclararActionPerformed

    private void jb_mostrarDialogAgregarVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_mostrarDialogAgregarVariableActionPerformed

        //mostrar ventana de agregar variable
        jd_crearVariable.setLocationRelativeTo(this);
        jd_crearVariable.setVisible(true);

    }//GEN-LAST:event_jb_mostrarDialogAgregarVariableActionPerformed

    private void jb_agregarVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarVariableActionPerformed
        // AGREGAR VARIABLE
        // Crear String variable
        // Agregar a arrayList variables
        // actualizar modelo

        if (jtf_nombreNuevaVariable.getText().isBlank()) {
            JOptionPane.showMessageDialog(jd_crearVariable, "Llenar todos los campos");
        } else {
            String nuevaVariable = "("
                    + jcb_tipoNuevaVariable.getSelectedItem()
                    + ")"
                    + jtf_nombreNuevaVariable.getText();

            listaVariables.add(nuevaVariable);

            jtf_nombreNuevaVariable.setText("");
            jd_crearVariable.setVisible(false);
            llenarJList(jl_variables);
            jl_variables.repaint();

        }


    }//GEN-LAST:event_jb_agregarVariableActionPerformed

    private void jb_opcionesFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_opcionesFinActionPerformed
        // BOTON FIN

        if (contBotonesFin > 0) {
            JOptionPane.showMessageDialog(jlp_diagramaFlujo, "Solo puede existir 1\n"
                    + "fin por programa");

        } else {
            BotonFin nuevoFin = (BotonFin) convertirABotonArrastrable(new BotonFin());
            botonesDiagramaFlujo.add(nuevoFin);
            contBotonesFin++;
            llenarJLayeredPane(jlp_diagramaFlujo);
            jlp_diagramaFlujo.repaint();
        }

    }//GEN-LAST:event_jb_opcionesFinActionPerformed

    private void jcb_crearOperacionVar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_crearOperacionVar1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jcb_crearOperacionVar1ActionPerformed

    private void jb_dialogCrearOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_dialogCrearOperacionActionPerformed
        // CREAR NUEVA OPERACION
        //nuevo boton usando los datos del dialog
        BotonDeclararOperacion nuevaOperacion = (BotonDeclararOperacion) convertirABotonArrastrable(new BotonDeclararOperacion(
                (String) jcb_crearOperacionVar1.getSelectedItem(),
                (String) jcb_crearOperacionVar2.getSelectedItem(),
                (String) jcb_crearOperacionOperador.getSelectedItem(),
                (String) jcb_crearOperacionResultado.getSelectedItem()));

        botonesDiagramaFlujo.add(nuevaOperacion);
        llenarJLayeredPane(jlp_diagramaFlujo);
        jlp_diagramaFlujo.repaint();
        jd_crearOperacion.setVisible(false);


    }//GEN-LAST:event_jb_dialogCrearOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFPrincipal().setVisible(true);
            }
        });
    }

    public JList llenarJList(JList lista) {
        DefaultListModel modeloLista = new DefaultListModel();

        for (String variable : listaVariables) {
            modeloLista.addElement(variable);
        }

        //jtf_nombreNuevaVariable.setText("");
        //jd_crearVariable.setVisible(false);
        lista.setModel(modeloLista);

        return lista;

    }

    public JLayeredPane llenarJLayeredPane(JLayeredPane panel) {
        panel.removeAll();
        for (JButton jButton : botonesDiagramaFlujo) {
            panel.add(jButton);
        }

        return panel;
    }

    // Create a JLabel that supports drag and drop
    //BORRAR usa transferhandler
    private JLabel createDraggableLabel(String text, int x, int y) {
        JLabel label = new JLabel(text);
        label.setBounds(x, y, 100, 30);

        // Set transfer handler to enable dragging
        label.setTransferHandler(new TransferHandler("text"));

        // Add mouse listener to initiate drag
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                System.out.println("pressed");
                JComponent comp = (JComponent) evt.getSource();
                TransferHandler handler = comp.getTransferHandler();
                handler.exportAsDrag(comp, evt, TransferHandler.MOVE);
            }
        });

        return label;
    }

    //crear boton arrastrable
    private JButton crearBotonArrastrable(String texto, Icon icono) {
        JButton boton = new JButton(texto, icono);
        boton.setHorizontalTextPosition(SwingConstants.CENTER);
        boton.setBounds(50, 50, 120, 120);

        final Point[] initialClick = new Point[1];

        boton.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {

                if (e.getButton() == 3) {

                    jpum_elemDiagramaFlujo.show(e.getComponent(), e.getX(), e.getY());
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                initialClick[0] = e.getPoint();

            }
        });

        boton.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // Get the button's current position
                int thisX = boton.getLocation().x;
                int thisY = boton.getLocation().y;

                // Calculate how much the mouse moved
                int xMoved = e.getX() - initialClick[0].x;
                int yMoved = e.getY() - initialClick[0].y;

                // Update the button's location
                int newX = thisX + xMoved;
                int newY = thisY + yMoved;
                boton.setLocation(newX, newY);
            }
        });

        return boton;
    }

    //convertir boton arrastrable
    public JButton convertirABotonArrastrable(JButton boton) {

        final Point[] initialClick = new Point[1];

        boton.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {

                if (e.getButton() == 3) {

                    jpum_elemDiagramaFlujo.show(e.getComponent(), e.getX(), e.getY());
                }
            }

            public void mousePressed(MouseEvent e) {
                initialClick[0] = e.getPoint();

            }
        });

        boton.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // Get the button's current position
                int thisX = boton.getLocation().x;
                int thisY = boton.getLocation().y;

                // Calculate how much the mouse moved
                int xMoved = e.getX() - initialClick[0].x;
                int yMoved = e.getY() - initialClick[0].y;

                // Update the button's location
                int newX = thisX + xMoved;
                int newY = thisY + yMoved;
                boton.setLocation(newX, newY);
            }
        });

        return boton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_agregarVariable;
    private javax.swing.JButton jb_dialogCrearOperacion;
    private javax.swing.JButton jb_fuenteColor;
    private javax.swing.JButton jb_generarCodigoFlujo;
    private javax.swing.JButton jb_mostrarDialogAgregarVariable;
    private javax.swing.JButton jb_opcionesConectorX;
    private javax.swing.JButton jb_opcionesConectorY;
    private javax.swing.JButton jb_opcionesDeclarar;
    private javax.swing.JButton jb_opcionesFin;
    private javax.swing.JButton jb_opcionesFor;
    private javax.swing.JButton jb_opcionesIf;
    private javax.swing.JButton jb_opcionesInicio;
    private javax.swing.JButton jb_opcionesSout;
    private javax.swing.JButton jb_opcionesWhile;
    private javax.swing.JButton jb_pegarElementoDiagramaFlujo;
    private javax.swing.JComboBox<String> jcb_crearOperacionOperador;
    private javax.swing.JComboBox<String> jcb_crearOperacionResultado;
    private javax.swing.JComboBox<String> jcb_crearOperacionVar1;
    private javax.swing.JComboBox<String> jcb_crearOperacionVar2;
    private javax.swing.JComboBox<String> jcb_fuenteEstilo;
    private javax.swing.JComboBox<String> jcb_fuenteFuente;
    private javax.swing.JComboBox<String> jcb_tipoNuevaVariable;
    private javax.swing.JDialog jd_crearOperacion;
    private javax.swing.JDialog jd_crearVariable;
    private javax.swing.JFrame jf_ventanaCodigo;
    private javax.swing.JList<String> jl_variables;
    private javax.swing.JLayeredPane jlp_diagramaClases;
    private javax.swing.JLayeredPane jlp_diagramaFlujo;
    private javax.swing.JMenu jm_principalArchivo;
    private javax.swing.JMenu jm_principalExportar;
    private javax.swing.JMenuBar jmb_principal;
    private javax.swing.JMenuItem jmi_archivoNuevo;
    private javax.swing.JMenuItem jmi_elemDiagFlAgregarPropiedad;
    private javax.swing.JMenuItem jmi_elemDiagFlCopiar;
    private javax.swing.JMenuItem jmi_elemDiagFlPropiedades;
    private javax.swing.JMenuItem jmi_elemDiagFljCambiarColor;
    private javax.swing.JMenuItem jmi_elemDiagFljCambiarTexto;
    private javax.swing.JMenuItem jmi_elemDiagFljEliminar;
    private javax.swing.JMenuItem jmi_exportarPDF;
    private javax.swing.JPanel jp_Diagrama;
    private javax.swing.JPanel jp_clases;
    private javax.swing.JPanel jp_codigo;
    private javax.swing.JPanel jp_diagramaOpciones;
    private javax.swing.JPanel jp_opcionesFuente;
    private javax.swing.JPanel jp_variables;
    private javax.swing.JPopupMenu jpum_elemDiagramaFlujo;
    private javax.swing.JSpinner js_fuenteTamaño;
    private javax.swing.JTree jt_clases;
    private javax.swing.JTextArea jta_codigoGenerado;
    private javax.swing.JTextField jtf_nombreNuevaVariable;
    private javax.swing.JTabbedPane jtp_diagramaCodigo;
    // End of variables declaration//GEN-END:variables
    private ArrayList<JButton> botonesDiagramaFlujo = new ArrayList();
    private ArrayList<String> listaVariables = new ArrayList();
    private int contBotonesInicio = 0;

    private int contBotonesFin = 0;

}
